{
 "title": "VMHost",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "VMHost",
    "query": "SELECT DISTINCT HostName FROM Hosts"
   }
  ]
 },
 "panels": [
  {
   "title": "VMHost CPU %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n\t$__timeEpoch(Timestamp),\r\n\tAVG(Value) AS Value,\r\n\tVMHost + ' - ' + MetricId as metric\r\nFROM\r\n\tdbo.tblHostPerfStats\r\n/* dirty read, we just want the data as quick as possible*/\r\nWITH (NOLOCK)\r\nWHERE\r\n\t$__timeFilter(Timestamp) AND\r\n\tMetricId = 'cpu.usage.Average' AND\r\n\tVMHost IN ($VMHost)\r\nGROUP BY\r\n\tVMHost,\r\n\tMetricId,\r\n\tUnit,\r\n\tTimestamp\r\n\r\nUNION\r\n\r\nSELECT\r\n\t$__timeEpoch(Timestamp),\r\n\tAVG(Value) AS Value,\r\n\tVMHost + ' - ' + MetricId as metric\r\nFROM\r\n\tdbo.tblHostPerfStats_Daily\r\n/* dirty read, we just want the data as quick as possible*/\r\nWITH (NOLOCK)\r\nWHERE\r\n\t$__timeFilter(Timestamp) AND\r\n\tMetricId = 'cpu.usage.Average' AND\r\n\tVMHost IN ($VMHost)\r\nGROUP BY\r\n\tVMHost,\r\n\tMetricId,\r\n\tUnit,\r\n\tTimestamp\r\n\r\nORDER BY\r\n  time ASC"
    }
   ]
  },
  {
   "title": "Read KBps",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n\t$__timeEpoch(Timestamp),\r\n\tAVG(Value) AS value,\r\n\tVMGuest + ' - ' + MetricId + ' (' + Unit + ')' AS metric\r\nFROM\r\n\tdbo.tblGuestPerfStats\r\n/* dirty read, we just want the data as quick as possible*/\r\nWITH (NOLOCK)\r\nWHERE\r\n\t$__timeFilter(Timestamp) AND\r\n\tMetricId = 'datastore.read.average' AND\r\n\tVMHost in ($VMHost)\r\nGROUP BY\r\n\tVMGuest,\r\n\tMetricId,\r\n\tUnit,\r\n\tTimestamp\r\n\r\nUNION\r\n\r\nSELECT\r\n\t$__timeEpoch(Timestamp),\r\n\tAVG(Value) AS value,\r\n\tVMGuest + ' - ' + MetricId + ' (' + Unit + ')' AS metric\r\nFROM\r\n\tdbo.tblGuestPerfStats_Daily\r\n/* dirty read, we just want the data as quick as possible*/\r\nWITH (NOLOCK)\r\nWHERE\r\n\t$__timeFilter(Timestamp) AND\r\n\tMetricId = 'datastore.read.average' AND\r\n\tVMHost in ($VMHost)\r\nGROUP BY\r\n\tVMGuest,\r\n\tMetricId,\r\n\tUnit,\r\n\tTimestamp\r\nORDER BY\r\n  time ASC"
    }
   ]
  },
  {
   "title": "Write KBps",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n\t$__timeEpoch(Timestamp),\r\n\tAVG(Value) AS value,\r\n\tVMGuest + ' - ' + MetricId + ' (' + Unit + ')' AS metric\r\nFROM\r\n\tdbo.tblGuestPerfStats\r\n/* dirty read, we just want the data as quick as possible*/\r\nWITH (NOLOCK)\r\nWHERE\r\n\t$__timeFilter(Timestamp) AND\r\n\tMetricId = 'datastore.write.average' AND\r\n\tVMHost in ($VMHost)\r\nGROUP BY\r\n\tVMGuest,\r\n\tMetricId,\r\n\tUnit,\r\n\tTimestamp\r\n\r\nUNION\r\n\r\nSELECT\r\n\t$__timeEpoch(Timestamp),\r\n\tAVG(Value) AS value,\r\n\tVMGuest + ' - ' + MetricId + ' (' + Unit + ')' AS metric\r\nFROM\r\n\tdbo.tblGuestPerfStats_Daily\r\n/* dirty read, we just want the data as quick as possible*/\r\nWITH (NOLOCK)\r\nWHERE\r\n\t$__timeFilter(Timestamp) AND\r\n\tMetricId = 'datastore.write.average' AND\r\n\tVMHost in ($VMHost)\r\nGROUP BY\r\n\tVMGuest,\r\n\tMetricId,\r\n\tUnit,\r\n\tTimestamp\r\nORDER BY\r\n  time ASC"
    }
   ]
  }
 ]
}