{
 "title": "Data Store",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "DS-01",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch(Timestamp),\n  (([CapacityGB] - [FreeSpaceGB]) / [CapacityGB]) * 100 as value,\n  '% Used' as metric\nFROM\n  tblDataStores\nWHERE\n  $__timeFilter(Timestamp) and DataStoreName = 'DS-01'\nORDER BY\n  Timestamp ASC"
    }
   ]
  },
  {
   "title": "DS-02",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch(Timestamp),\n  (([CapacityGB] - [FreeSpaceGB]) / [CapacityGB]) * 100 as value,\n  '% Used' as metric\nFROM\n  tblDataStores\nWHERE\n  $__timeFilter(Timestamp) and DataStoreName = 'DS-02'\nORDER BY\n  Timestamp ASC"
    }
   ]
  },
  {
   "title": "DS-Logs",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch(Timestamp),\n  (([CapacityGB] - [FreeSpaceGB]) / [CapacityGB]) * 100 as value,\n  '% Used' as metric\nFROM\n  tblDataStores\nWHERE\n  $__timeFilter(Timestamp) and DataStoreName = 'DS-Logs'\nORDER BY\n  Timestamp ASC"
    }
   ]
  },
  {
   "title": "DS-SSD",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch(Timestamp),\n  (([CapacityGB] - [FreeSpaceGB]) / [CapacityGB]) * 100 as value,\n  '% Used' as metric\nFROM\n  tblDataStores\nWHERE\n  $__timeFilter(Timestamp) and DataStoreName = 'DS-SSD'\nORDER BY\n  Timestamp ASC"
    }
   ]
  },
  {
   "title": "Read/Write KBps",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n\t$__timeEpoch(Timestamp),\r\n\tAVG(Value) AS Value,\r\n\tVMHost + '-' + MetricId as metric\r\nFROM\r\n\tdbo.tblHostPerfStats\r\n/* dirty read, we just want the data as quick as possible*/\r\nWITH (NOLOCK)\r\nWHERE\r\n\t$__timeFilter(Timestamp) AND\r\n\tMetricId = 'datastore.read.average'\r\nGROUP BY\r\n\tVMHost,\r\n\tMetricId,\r\n\tUnit,\r\n\tTimestamp\r\n\r\nUNION\r\n\r\nSELECT\r\n\t$__timeEpoch(Timestamp),\r\n\tAVG(Value) AS Value,\r\n\tVMHost + '-' + MetricId as metric\r\nFROM\r\n\tdbo.tblHostPerfStats_Daily\r\n/* dirty read, we just want the data as quick as possible*/\r\nWITH (NOLOCK)\r\nWHERE\r\n\t$__timeFilter(Timestamp) AND\r\n\tMetricId = 'datastore.read.average'\r\nGROUP BY\r\n\tVMHost,\r\n\tMetricId,\r\n\tUnit,\r\n\tTimestamp\r\n\r\nORDER BY\r\n  time ASC"
    },
    {
     "rawSql": "SELECT\r\n\t$__timeEpoch(Timestamp),\r\n\tAVG(Value) AS Value,\r\n\tVMHost + '-' + MetricId as metric\r\nFROM\r\n\tdbo.tblHostPerfStats\r\n/* dirty read, we just want the data as quick as possible*/\r\nWITH (NOLOCK)\r\nWHERE\r\n\t$__timeFilter(Timestamp) AND\r\n\tMetricId = 'datastore.write.average'\r\nGROUP BY\r\n\tVMHost,\r\n\tMetricId,\r\n\tUnit,\r\n\tTimestamp\r\n\r\nUNION\r\n\r\nSELECT\r\n\t$__timeEpoch(Timestamp),\r\n\tAVG(Value) AS Value,\r\n\tVMHost + '-' + MetricId as metric\r\nFROM\r\n\tdbo.tblHostPerfStats_Daily\r\n/* dirty read, we just want the data as quick as possible*/\r\nWITH (NOLOCK)\r\nWHERE\r\n\t$__timeFilter(Timestamp) AND\r\n\tMetricId = 'datastore.write.average'\r\nGROUP BY\r\n\tVMHost,\r\n\tMetricId,\r\n\tUnit,\r\n\tTimestamp\r\n\r\nORDER BY\r\n  time ASC"
    }
   ]
  },
  {
   "title": "# Read/Write",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n\t$__timeEpoch(Timestamp),\r\n\tAVG(Value) AS Value,\r\n\tVMHost + '-' + MetricId as metric\r\nFROM\r\n\tdbo.tblHostPerfStats\r\n/* dirty read, we just want the data as quick as possible*/\r\nWITH (NOLOCK)\r\nWHERE\r\n\t$__timeFilter(Timestamp) AND\r\n\tMetricId = 'datastore.numberwriteaveraged.average'\r\nGROUP BY\r\n\tVMHost,\r\n\tMetricId,\r\n\tUnit,\r\n\tTimestamp\r\n\r\nUNION\r\n\r\nSELECT\r\n\t$__timeEpoch(Timestamp),\r\n\tAVG(Value) AS Value,\r\n\tVMHost + '-' + MetricId as metric\r\nFROM\r\n\tdbo.tblHostPerfStats_Daily\r\n/* dirty read, we just want the data as quick as possible*/\r\nWITH (NOLOCK)\r\nWHERE\r\n\t$__timeFilter(Timestamp) AND\r\n\tMetricId = 'datastore.numberwriteaveraged.average'\r\nGROUP BY\r\n\tVMHost,\r\n\tMetricId,\r\n\tUnit,\r\n\tTimestamp\r\n\r\nORDER BY\r\n  time ASC"
    },
    {
     "rawSql": "SELECT\r\n\t$__timeEpoch(Timestamp),\r\n\tAVG(Value) AS Value,\r\n\tVMHost + '-' + MetricId as metric\r\nFROM\r\n\tdbo.tblHostPerfStats\r\n/* dirty read, we just want the data as quick as possible*/\r\nWITH (NOLOCK)\r\nWHERE\r\n\t$__timeFilter(Timestamp) AND\r\n\tMetricId = 'datastore.numberreadaveraged.average'\r\nGROUP BY\r\n\tVMHost,\r\n\tMetricId,\r\n\tUnit,\r\n\tTimestamp\r\n\r\nUNION\r\n\r\nSELECT\r\n\t$__timeEpoch(Timestamp),\r\n\tAVG(Value) AS Value,\r\n\tVMHost + '-' + MetricId as metric\r\nFROM\r\n\tdbo.tblHostPerfStats_Daily\r\n/* dirty read, we just want the data as quick as possible*/\r\nWITH (NOLOCK)\r\nWHERE\r\n\t$__timeFilter(Timestamp) AND\r\n\tMetricId = 'datastore.numberreadaveraged.average'\r\nGROUP BY\r\n\tVMHost,\r\n\tMetricId,\r\n\tUnit,\r\n\tTimestamp\r\n\r\nORDER BY\r\n  time ASC"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n\t$__timeEpoch(Timestamp),\r\n\tAVG(Value) AS Value,\r\n\tVMHost + '-' + MetricId as metric\r\nFROM\r\n\tdbo.tblHostPerfStats\r\n/* dirty read, we just want the data as quick as possible*/\r\nWITH (NOLOCK)\r\nWHERE\r\n\t$__timeFilter(Timestamp) AND\r\n\tMetricId = 'datastore.totalwritelatency.average'\r\nGROUP BY\r\n\tVMHost,\r\n\tMetricId,\r\n\tUnit,\r\n\tTimestamp\r\n\r\nUNION\r\n\r\nSELECT\r\n\t$__timeEpoch(Timestamp),\r\n\tAVG(Value) AS Value,\r\n\tVMHost + '-' + MetricId as metric\r\nFROM\r\n\tdbo.tblHostPerfStats_Daily\r\n/* dirty read, we just want the data as quick as possible*/\r\nWITH (NOLOCK)\r\nWHERE\r\n\t$__timeFilter(Timestamp) AND\r\n\tMetricId = 'datastore.totalwritelatency.average'\r\nGROUP BY\r\n\tVMHost,\r\n\tMetricId,\r\n\tUnit,\r\n\tTimestamp\r\n\r\nORDER BY\r\n  time ASC"
    },
    {
     "rawSql": "SELECT\r\n\t$__timeEpoch(Timestamp),\r\n\tAVG(Value) AS Value,\r\n\tVMHost + '-' + MetricId as metric\r\nFROM\r\n\tdbo.tblHostPerfStats\r\n/* dirty read, we just want the data as quick as possible*/\r\nWITH (NOLOCK)\r\nWHERE\r\n\t$__timeFilter(Timestamp) AND\r\n\tMetricId = 'datastore.totalreadlatency.average'\r\nGROUP BY\r\n\tVMHost,\r\n\tMetricId,\r\n\tUnit,\r\n\tTimestamp\r\n\r\nUNION\r\n\r\nSELECT\r\n\t$__timeEpoch(Timestamp),\r\n\tAVG(Value) AS Value,\r\n\tVMHost + '-' + MetricId as metric\r\nFROM\r\n\tdbo.tblHostPerfStats_Daily\r\n/* dirty read, we just want the data as quick as possible*/\r\nWITH (NOLOCK)\r\nWHERE\r\n\t$__timeFilter(Timestamp) AND\r\n\tMetricId = 'datastore.totalreadlatency.average'\r\nGROUP BY\r\n\tVMHost,\r\n\tMetricId,\r\n\tUnit,\r\n\tTimestamp\r\n\r\nORDER BY\r\n  time ASC"
    }
   ]
  }
 ]
}