
SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [tblGuestPerfStats_MetricIdTimeStampVMHost_Include_Value] ON [dbo].[tblGuestPerfStats]
(
	[MetricId] ASC,
	[Timestamp] ASC,
	[VMHost] ASC
)
INCLUDE ( 	[Value]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO